vich_uploader:
    db_driver: orm
    mappings:
        parkings_images:
            uri_prefix: /images/parkings
            upload_destination: '%kernel.project_dir%/public/images/parkings'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
